export const types = Object.freeze({
    POSTS_START_FETCHING: 'POSTS_START_FETCHING',
    POSTS_STOP_FETCHING: 'POSTS_STOP_FETCHING',
    POSTS_FILL: 'POSTS_FILL',
    POSTS_SET_FETCHING_ERROR: 'POSTS_SET_FETCHING_ERROR',
    POSTS_FETCH_ASYNC: 'POSTS_FETCH_ASYNC',
    
    POST_START_FETCHING: 'POST_START_FETCHING',
    POST_STOP_FETCHING: 'POST_STOP_FETCHING',
    POST_FILL: 'POST_FILL',
    POST_SET_FETCHING_ERROR: 'POST_SET_FETCHING_ERROR',
    POST_FETCH_ASYNC: 'POST_FETCH_ASYNC'
});
