export const types = Object.freeze({
    COMMENTS_START_FETCHING: 'COMMENTS_START_FETCHING',
    COMMENTS_STOP_FETCHING: 'COMMENTS_STOP_FETCHING',
    COMMENTS_FILL: 'COMMENTS_FILL',
    COMMENTS_SET_FETCHING_ERROR: 'COMMENTS_SET_FETCHING_ERROR',
    COMMENTS_FETCH_ASYNC: 'COMMENTS_FETCH_ASYNC',
    
    COMMENT_START_FETCHING: 'COMMENT_START_FETCHING',
    COMMENT_STOP_FETCHING: 'COMMENT_STOP_FETCHING',
    COMMENT_FILL: 'COMMENT_FILL',
    COMMENT_SET_FETCHING_ERROR: 'COMMENT_SET_FETCHING_ERROR',
    COMMENT_FETCH_ASYNC: 'COMMENT_FETCH_ASYNC'
});
