export const types = Object.freeze({
    // Tasks
    TASKS_START_FETCHING: 'TASKS_START_FETCHING',
    TASKS_STOP_FETCHING: 'TASKS_STOP_FETCHING',
    TASKS_SET_FETCHING_ERROR: 'TASKS_SET_FETCHING_ERROR',
    TASKS_FETCH_ASYNC: 'TASKS_FETCH_ASYNC',
    TASKS_FILL: 'TASKS_FILL',
    
    // Single Task
    TASK_START_FETCHING: 'TASK_START_FETCHING',
    TASK_STOP_FETCHING: 'TASK_STOP_FETCHING',
    TASK_SET_FETCHING_ERROR: 'TASK_SET_FETCHING_ERROR',
    TASK_FETCH_ASYNC: 'TASK_FETCH_ASYNC',
    TASK_FILL: 'TASK_FILL',
});
