export const types = Object.freeze({
    FORM_START_EDITING: 'FORM_START_EDITING',
    
    FORM_ERROR_DATA: 'FORM_ERROR_DATA',
    FORM_POST_DATA: 'FORM_POST_DATA',
    FORM_GET_DATA: 'FORM_GET_DATA',
    FORM_DELETE_DATA: 'FORM_DELETE_DATA',
    FORM_UPDATE_DATA: 'FORM_UPDATE_DATA',
    FORM_FETCH_ASYNC: 'POSTS_FETCH_ASYNC',
});
